export type AgentToolName =
  | 'inspect_graph'
  | 'create_block'
  | 'update_block'
  | 'delete_block'
  | 'create_terminal_group'
  | 'update_terminal_group'
  | 'delete_terminal_group'
  | 'update_terminal_execution_config'
  | 'connect_terminal_blocks'
  | 'disconnect_terminal_blocks'
  | 'inspect_terminal_workflow_plan'
