export type AgentToolName =
  | 'inspect_graph'
  | 'create_block'
  | 'create_terminal'
  | 'create_terminal_workflow'
  | 'create_terminal_set'
  | 'update_block'
  | 'delete_block'
  | 'create_terminal_group'
  | 'move_terminal_workflow_to_group'
  | 'update_terminal_group'
  | 'delete_terminal_group'
  | 'update_terminal_execution_config'
  | 'connect_terminal_blocks'
  | 'disconnect_terminal_blocks'
  | 'inspect_terminal_workflow_plan'
  | 'arrange_terminal_layout'
